recipes.replaceAllOccurences(<minecraft:bookshelf>, <ore:bookshelf>);
recipes.replaceAllOccurences(<minecraft:feather>, <ore:feather>);
recipes.replaceAllOccurences(<minecraft:leather>, <ore:leather>);
recipes.replaceAllOccurences(<minecraft:egg>, <ore:egg>);
recipes.replaceAllOccurences(<minecraft:book>, <ore:book>);
recipes.replaceAllOccurences(<minecraft:rotten_flesh>, <ore:listAllmeatrotten>);
//recipes.replaceAllOccurences(<minecraft:iron_ingot>, <ore:ingotIron>);
recipes.replaceAllOccurences(<notenoughroofs:copper_ingot>, <ore:ingotCopper>);
recipes.replaceAllOccurences(<minecraft:wooden_pressure_plate>, <ore:pressurePlateWood>);